/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#acabaa",
        "primary-dim": "#b0b2ff",
        "on-error": "#490013",
        "on-primary-container": "#ccccff",
        "surface-container-highest": "#252626",
        "on-secondary-fixed": "#403f43",
        "inverse-on-surface": "#565555",
        "secondary-fixed": "#e5e1e6",
        "surface-bright": "#2b2c2c",
        "secondary-fixed-dim": "#d6d3d8",
        "on-background": "#e7e5e5",
        "on-tertiary": "#4a536c",
        "tertiary-container": "#ced6f5",
        error: "#ec7c8a",
        "tertiary-fixed-dim": "#c0c9e6",
        "secondary-container": "#3c3b3f",
        "error-container": "#7f2737",
        "on-primary": "#2724b8",
        "surface-container-high": "#1f2020",
        surface: "#0e0e0e",
        "primary-fixed-dim": "#d1d0ff",
        "on-secondary-container": "#c1bec3",
        "on-tertiary-container": "#424a63",
        "surface-container-low": "#131313",
        "on-surface": "#e7e5e5",
        "on-primary-fixed": "#2622b7",
        "on-error-container": "#ff97a3",
        "primary-container": "#2f2ebe",
        "on-primary-fixed-variant": "#4647d3",
        "surface-variant": "#252626",
        primary: "#c0c1ff",
        "secondary-dim": "#9f9da1",
        outline: "#767575",
        secondary: "#9f9da1",
        "inverse-surface": "#fcf9f8",
        "surface-tint": "#c0c1ff",
        "on-tertiary-fixed-variant": "#4b546d",
        tertiary: "#dee5ff",
        "surface-container": "#191a1a",
        "on-secondary-fixed-variant": "#5c5b5f",
        "on-secondary": "#202023",
        "inverse-primary": "#494bd7",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#0e0e0e",
        background: "#0e0e0e",
        "error-dim": "#b95463",
        "outline-variant": "#484848",
        "tertiary-fixed": "#ced6f5",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#c0c9e6",
        "on-tertiary-fixed": "#2f384f",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
